name: CI

on:
  workflow_run:
    workflows: ['Success CI', 'Fail CI']
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: echo "Pass"
